# Load packages
library(vegan)
library(tidyverse)
library(lubridate)
library(ggrepel)
library(patchwork)

set.seed(12)
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
source('SSBcode/00_LoadData.R')
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
total.pp = pp |> arrange(sampledate) |> 
  group_by(sample_date = sampledate) |> 
  summarise(PP.Biovolume = log(sum(biovolume_conc, na.rm = T))) 

pp.biovolume = pp |> filter(division %in% c('Chlorophyta','Cyanophyta')) |> 
  group_by(sample_date = sampledate, division) |> 
  summarise(total = log(sum(biovolume_conc))) |> 
  pivot_wider(names_from = division, values_from = total) |> 
  left_join(total.pp)

useVars = env.vars |> left_join(pp.biovolume) |> 
  filter(sample_date %in% unique(zoops$sample_date)) |> 
  select(-Lake, -lakeid, -Sensor, -depth, -Depth_m, -Temp_C, -sample_date) |> 
  setNames(c('Snow','Total Ice','White Ice',
             'Black Ice','Secchi','Chl-a 0 m','Light 0.7 m','Chlorophyta','Cyanophyta','PP.Biovolume'))

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#### Group phytoplankton division ####
df.genus = zoops |> arrange(sample_date) |> 
  group_by(lakeid, sample_date, genus) |> 
  summarise(density = sum(density, na.rm = T)) |> 
  group_by(genus) |> 
  mutate(n = n()) |> 
  filter(n >= 3)
table(df.genus$genus)

# total = zoops |> arrange(sample_date) |> 
#   group_by(lakeid, sample_date) |> 
#   summarise(Tot.Density = sum(density, na.rm = T))

df.genus.wide = df.genus |> select(-n) |> 
  pivot_wider(names_from = genus,
              values_from = density,
              values_fill = 0) |>
  ungroup() |> 
  select(-lakeid, - sample_date)
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cca_zoop <- cca(df.genus.wide ~ 
                 PP.Biovolume + Chlorophyta + Cyanophyta + `White Ice` + `Black Ice`,
                data = useVars, na.action = 'na.exclude') 

# Testing the significance of the CCA model:
anova.cca(cca_zoop)
# Testing the significance of terms (environmental variables):
anova.cca(cca_zoop, by="terms")
# Testing the significance of CCA axes (at least the first two or three should present a significant p value):
anova.cca(cca_zoop, by="axis")

#Get CCA scores
df_species  <- data.frame(summary(cca_zoop)$species[,1:2]) |> 
  mutate(label = rownames(summary(cca_zoop)$species))# get the species CC1 and CC2 scores
df_environ  <- data.frame(scores(cca_zoop, display = 'bp')) #get the environment vars CC1 and CC2 scores
rownames(df_environ) = gsub(pattern = '`',replacement = '', rownames(df_environ))
CCA1_varex <- round(summary(cca_zoop)$cont$importance[2,1]*100,2) #Get percentage of variance explained by first axis
CCA2_varex <- round(summary(cca_zoop)$cont$importance[2,2]*100,2) #Get percentage of variance explained by second axis
# cca_labels = names(df.division.wide)
# Set a scaling variable to multiply the CCA values, in order to get a very similar plot to the the one generated by plot(cca_model). 
# Adjust it according to your data
scaling_factor <- 2

# CCA PLOT
my.colors <- c("#94C971", "#226231", "#B5D6E2", "#1D3E68", 
               # "#FFA17F", "#BF4904", "#EBADBE",
               "#702539", 
               # "#C4AED0",
               "#8A629E", 
               # "#D23131", "#EFD556",
               "#B99A00", 'black')

cca.plot3 = ggplot(df_species, aes(x=CCA1, y=CCA2)) + 
  geom_hline(yintercept=0, linetype="dashed", size = 0.3) +
  geom_vline(xintercept=0, linetype="dashed", size = 0.3) +
  #Add environmental vars arrows
  geom_segment(data = df_environ, 
               aes(x=0, #Starting coordinate in CCA1 = 0 
                   xend = CCA1*scaling_factor,#Ending coordinate in CCA1  
                   y=0, #Start in CCA2 = 0
                   yend = CCA2*scaling_factor), #Ending coordinate in CCA2 
               color = "lightblue4", #set color
               arrow = arrow(length=unit(0.02,"npc"))) + #Set the size of the lines that form the tip of the arrow
  #Add species text
  geom_point(data = df_species, aes(x=CCA1, y = CCA2, col = label), size = 3) +
  scale_color_manual(values = my.colors, name = 'Genus') + 
  #Add environmental vars text
  geom_label_repel(data = df_environ, 
                   aes(x = CCA1*scaling_factor, y = CCA2*scaling_factor),
                   label = rownames(df_environ),
                   label.padding = 0.1,
                   nudge_y = -1, color="lightblue4", fill = alpha("white", 0.9),
                   segment.size = 0.2, size = 2.5) +
  #Set x and y axis titles
  labs(x=paste0("CCA1 (",CCA1_varex," %)"),
       y=paste0("CCA2 (",CCA2_varex," %)"),
       title = 'Zooplankton') +
  #Set bw theme
  theme_bw(base_size = 9) +
  theme(legend.text = element_text(size = 7), 
        plot.title = element_text(size = 8, color = 'gold', face = 2, margin=margin(0,0,1,0)),
        plot.margin = unit(c(0,0,0,0), "cm"),
        legend.margin = margin(c(0,0,0,0), unit = "cm"),
        legend.key.width = unit(0.1,"cm"),
        legend.key.height = unit(0.15,"cm")); cca.plot3

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#### Group by morpho group ####
df.group = zoops |> arrange(sample_date) |> 
  group_by(lakeid, sample_date, trophi_grouping) |> 
  summarise(density = sum(density, na.rm = T)) 

df.group.wide = df.group |> 
  pivot_wider(names_from = trophi_grouping,
              values_from = density,
              values_fill = 0) |>
  ungroup() |> 
  select(-lakeid, - sample_date)
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cca_zoop.group <- cca(df.group.wide ~ 
                        PP.Biovolume + Chlorophyta + Cyanophyta + `White Ice` + `Black Ice`,
                      data = useVars, na.action = 'na.exclude') 

# Testing the significance of the CCA model:
anova.cca(cca_zoop.group, model = 'direct')
# Testing the significance of terms (environmental variables):
anova.cca(cca_zoop.group, by="terms")
# Testing the significance of CCA axes (at least the first two or three should present a significant p value):
anova.cca(cca_zoop.group, by="axis")

#Get CCA scores
df_species  <- data.frame(summary(cca_zoop.group)$species[,1:2]) |> 
  mutate(label = rownames(summary(cca_zoop.group)$species))# get the species CC1 and CC2 scores
# get the species CC1 and CC2 scores
df_environ  <- data.frame(scores(cca_zoop.group, display = 'bp')) #get the environment vars CC1 and CC2 scores
rownames(df_environ) = gsub(pattern = '`',replacement = '', rownames(df_environ))
CCA1_varex <- round(summary(cca_zoop.group)$cont$importance[2,1]*100,2) #Get percentage of variance explained by first axis
CCA2_varex <- round(summary(cca_zoop.group)$cont$importance[2,2]*100,2) #Get percentage of variance explained by second axis
# Set a scaling variable to multiply the CCA values, in order to get a very similar plot to the the one generated by plot(cca_model). 
# Adjust it according to your data
scaling_factor <- 2

# Colors 
my.colors <- c("#94C971", "#226231",
               "#FFA17F",
               "#B5D6E2", "#1D3E68")
# CCA PLOT

cca.plot4 = ggplot(df_species, aes(x=CCA1, y=CCA2)) + 
  geom_hline(yintercept=0, linetype="dashed", size = 0.3) +
  geom_vline(xintercept=0, linetype="dashed", size = 0.3) +
  #Add environmental vars arrows
  geom_segment(data = df_environ, 
               aes(x=0, #Starting coordinate in CCA1 = 0 
                   xend = CCA1*scaling_factor,#Ending coordinate in CCA1  
                   y=0, #Start in CCA2 = 0
                   yend = CCA2*scaling_factor), #Ending coordinate in CCA2 
               color = "lightblue4", #set color
               arrow = arrow(length=unit(0.02,"npc"))) + #Set the size of the lines that form the tip of the arrow
  #Add species text
  geom_point(data = df_species, aes(x=CCA1, y = CCA2, col = label), size = 3) +
  # geom_text_repel(data = df_species, aes(x=CCA1, y = CCA2, col = label, label = label), #Scores in CCA1 and CCA2 to add species text
  #                 size = 2.5,
  #                 nudge_x = 0.1, nudge_y = -0.05, 
  #                 # direction = "y", 
  #                 hjust = 0,
  #                 segment.size = 0.2) +
  scale_color_manual(values = my.colors, name = 'Trophi Group') + 
  #Add environmental vars text
  geom_label_repel(data = df_environ, 
                   aes(x = CCA1*scaling_factor, y = CCA2*scaling_factor),
                   label = rownames(df_environ),
                   label.padding = 0.1,
                   nudge_y = -0.3, color="lightblue4", fill = alpha("white", 0.9),
                   min.segment.length = 0.2,
                   segment.size = 0.2, size = 2.2) +
  #Set x and y axis titles
  labs(x=paste0("CCA1 (",CCA1_varex," %)"),
       y=paste0("CCA2 (",CCA2_varex," %)"),
       title = 'Zooplankton') +
  #Set bw theme
  theme_bw(base_size = 9) +
  theme(legend.text = element_text(size = 7), 
        plot.title = element_text(size = 8, color = 'gold', face = 2, margin=margin(0,0,1,0)),
        plot.margin = unit(c(0,0,0,0), "cm"),
        legend.margin = margin(c(0,0,0,0), unit = "cm"),
        legend.key.width = unit(0.1,"cm"),
        legend.key.height = unit(0.15,"cm")); cca.plot4
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# # combine plots ####
# cca.plot3 + cca.plot4 + plot_layout(widths = c(0.5,0.5)) +
#   plot_annotation(tag_levels = 'a', tag_suffix = ')') & 
#   theme(plot.tag = element_text(size  = 8))
# 
# ggsave('SSBfigures/Figure7_cca_zooplankton.png', width = 6.5, height = 2.5, dpi = 500)  
# #####

# combine with phytoplankton plots ####
source('SSBcode/Figure7_RDA_phytoplankton.R')
(rda.plot1 + rda.plot2) / (cca.plot3 + cca.plot4) + 
  plot_annotation(tag_levels = 'a', tag_suffix = ')') & 
  theme(plot.tag = element_text(size  = 8))

ggsave('SSBfigures/Figure7_CCA2.png', width = 6.5, height = 4, dpi = 500)  
#####
